# Generated by Django 3.0.6 on 2020-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('n_persons', models.IntegerField()),
                ('n_date', models.DateField()),
                ('n_time', models.TimeField()),
            ],
        ),
    ]
