# Generated by Django 3.0.6 on 2020-05-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categery',
            options={'verbose_name': 'categery', 'verbose_name_plural': 'categeries'},
        ),
        migrations.AddField(
            model_name='meal',
            name='categery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Categery'),
        ),
    ]
